name: Build and Push Docker Image to GHCR on Dockerfile Change 

on: 
 push: 
   branches: [ "main" ] 
   paths: 
     - 'Dockerfile' 
 workflow_dispatch: 

jobs: 
 build-and-push: 
   runs-on: ubuntu-latest 
   permissions: 
     contents: read 
     packages: write 

   steps: 
     # Step 1: Checkout repository 
     - name: Checkout repository 
       uses: actions/checkout@v4 

     # Step 2: Aggressive Disk Space Cleanup 
     - name: Aggressive Disk Space Cleanup
       run: | 
         echo "Initial disk space:" 
         df -h 
         sudo rm -rf /usr/share/dotnet 
         sudo rm -rf /usr/local/lib/android 
         sudo rm -rf /opt/ghc 
         sudo rm -rf /opt/hostedtoolcache/CodeQL 
         sudo rm -rf /usr/local/share/boost
         sudo docker image prune --all --force
         sudo docker builder prune -a -f
         echo "Disk space after cleanup:" 
         df -h 

     # Step 3: Log in to ghcr.io 
     - name: Log in to ghcr.io 
       uses: docker/login-action@v3 
       with: 
         registry: ghcr.io 
         username: ${{ github.actor }} 
         password: ${{ secrets.GITHUB_TOKEN }} 

     # Step 4: Extract Docker metadata 
     - name: Extract Docker metadata 
       id: meta 
       uses: docker/metadata-action@v5 
       with: 
         images: ghcr.io/${{ github.repository }} 

     # Step 5: Build and push 
     - name: Build and push 
       uses: docker/build-push-action@v5 
       with: 
         context: . 
         push: true # This is set to true to publish the image 
         tags: ${{ steps.meta.outputs.tags }} 
         labels: ${{ steps.meta.outputs.labels }} 
