# .github/workflows/docker-build.yml

name: Build and Push Docker Image to GHCR

# This workflow runs on every push to the main branch
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Grant the job permission to write to ghcr.io
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to the GitHub Container Registry (ghcr.io)
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # GITHUB_TOKEN is a special, automatically-generated secret.
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extract metadata for the Docker image, including tags
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      # 4. Build the image and push it to GHCR
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # The tags are generated in the previous step
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
