name: Build and Push Docker Image to GHCR on Dockerfile Change 

on: 
 push: 
   branches: [ "main" ] 
   paths: 
     - 'Dockerfile' 
 workflow_dispatch: 

jobs: 
 build-and-push: 
   runs-on: self-hosted
   permissions: 
     contents: read 
     packages: write 

   steps: 
     # Step 1: Checkout repository 
     - name: Checkout repository 
       uses: actions/checkout@v4 

     # Step 2: Log in to ghcr.io 
     - name: Log in to ghcr.io 
       uses: docker/login-action@v3 
       with: 
         registry: ghcr.io 
         username: ${{ github.actor }} 
         password: ${{ secrets.GITHUB_TOKEN }} 

     # Step 3: Extract Docker metadata 
     - name: Extract Docker metadata 
       id: meta 
       uses: docker/metadata-action@v5 
       with: 
         images: ghcr.io/${{ github.repository }} 

     # Step 4: Build and push 
     - name: Build and push 
       uses: docker/build-push-action@v5 
       with: 
         context: . 
         push: true # This is set to true to publish the image 
         tags: ${{ steps.meta.outputs.tags }} 
         labels: ${{ steps.meta.outputs.labels }} 
